language: swift
osx_image: xcode9.4
branches:
  only:
    - master
env:
  global:
  - WORKSPACE=MarkovModel.xcworkspace
  - SCHEME=MarkovModel
  - DESTINATION='platform=iOS Simulator,name=iPhone X,OS=11.4'
before_install:
  - gem install xcpretty --no-rdoc --no-ri --no-document --quiet
script:
  - set -o pipefail
  - xcodebuild -version
  - xcodebuild -showsdks
  - xcodebuild clean test -workspace "$WORKSPACE" -scheme "$SCHEME" -destination "$DESTINATION" -configuration 'Debug' | xcpretty
after_success:
  - bash <(curl -s https://codecov.io/bash)
